  back40roster:
    container_name: back40roster
    image: my40kroaster_server:local
    restart: always
    environment:
      ConnectionStrings__DefaultConnection: Server=*;Port=*;Database=*;User=*;Password=*
      Jwt__Key: $${JWT_KEY:*}
      Jwt__Issuer: *
      Jwt__Audience: *
      GOOGLE_CLIENT_ID: *

  front40roster:
    container_name: front40roster
    image: my40kroaster_front:local
    restart: always
    environment:
      VITE_GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    depends_on:
      - back40roster

  mariadb40roster:
    container_name: mariadb40roster
    image: mariadb:local
    environment:
      MYSQL_ROOT_PASSWORD: *
      MYSQL_DATABASE: *
      MYSQL_USER: *
      MYSQL_PASSWORD: *
    restart: always

